name: dbt_dwh
profile: dbt_dwh
version: '1.0.0'
config-version: 2

profile: 'dbt_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  load_date: '2024-11-11'
  # tpch_size: 10 #1, 10, 100, 1000, 10000
  
models:
  dbt_dwh:
    raw:
      tags:
        - 'raw'
      materialized: view
      +schema: dwh_detailed
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
      +schema: dwh_detailed
    raw_vault:
      +schema: dwh_detailed
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'links'
      sats:
        tags:
          - 'satellite'    

clean-targets:
    - "target"
    - "dbt_packages"
  